### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property orders has not been initialized

### ISSUE THREAD

**Issue by alessandro-basso-pdl** [RadiusNetworks/flybuy-android#24]
Hello,
Using SDK version 2.9.2, we are seeing the following exception in our Crashlytics logs, caused by the `lateinit property orders` not initialized:
```
Fatal Exception: java.lang.RuntimeException
Unable to create service com.radiusnetworks.flybuy.sdk.pickup.service.LocationService: kotlin.UninitializedPropertyAccessException: lateinit property orders has not been initialized
```
Full stack trace:
```
Fatal Exception: java.lang.RuntimeException: Unable to create service com.radiusnetworks.flybuy.sdk.pickup.service.LocationService: kotlin.UninitializedPropertyAccessException: lateinit property orders has not been initialized
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:5111)
       at android.app.ActivityThread.-$$Nest$mhandleCreateService()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)



```
Caused by kotlin.UninitializedPropertyAccessException
lateinit property orders has not been initialized
```
Full stack trace:
```
Caused by kotlin.UninitializedPropertyAccessException: lateinit property orders has not been initialized
       at com.radiusnetworks.flybuy.sdk.FlyBuyCore.getOrders(FlyBuyCore.kt:1)
       at com.radiusnetworks.flybuy.sdk.pickup.service.a.<init>(BaseLocationService.kt:103)
       at com.radiusnetworks.flybuy.sdk.pickup.service.LocationService.<init>(LocationService.kt)
       at java.lang.Class.newInstance(Class.java)
       at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
       at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:5073)
       at android.app.ActivityThread.-$$Nest$mhandleCreateService()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

In general, FlyBuy works fine within the app. The above issue is affecting a minority of uses in production. Steps to reproduce the issue are not known.
Please recommend which version of the SDK addresses the issue. Thanks!

**Comment by botnerd** [comment]
Thank you for the detailed crash information. We have seen this type of crash when the app is not calling `FlyBuyCore.configure(...)` in `Application.onCreate(...)`. `FlyBuyCore.configure(...)` makes sure those variables are initialized within the SDK before anything else uses them. Can you confirm that your app is initializing the Flybuy SDK in `Application.onCreate()`?

**Comment by botnerd** [comment]
That's helpful. If you are targeting API 34, you need to use at least v2.10.0 of the SDK (although we always recommend updating to the latest whenever possible). Note that there are a couple of breaking changes (although easy to upgrade) for gradle and java 8 time libraries. Instructions are provided at https://www.radiusnetworks.com/developers/flybuy/#/sdk-2.0/android-14. If you continue to see the problem after updating, please let us know.

**Comment by botnerd** [comment]
Closing this issue as stale. If you continue to have issues, please open a new issue.
